### PR TITLE
Integrate libsquash

### PR DESCRIPTION
**Pull request by rafecolton**
This pull request integrates https://github.com/winchman/libsquash, which results in the following changes:
- `sudo` is no longer required
- remove dependency on external `tar` binary
- remove dependency on https://github.com/docker/docker
- layer data is no longer written to disk
- binaries can now be released for both Darwin (Mac OS X) and Linux without any special install instructions

There are a couple of things that still need to be done / need comments before this pull request can be merged:
- [ ] reintroduce tagging functionality by writing the `repositories` file - this will require an addition to `libsquash` first
- [ ] reintroduce `-from` flag - this will also require an addition to `libsquash`
- [ ] remove `TODO.md` once the above items are addressed

### CODE REVIEW

**Comment by jwilder** [comment]
The first image I tried fails w/
```
Tarring new image to STDOUT
ERROR: unable to determine last layer in image
time="2015-01-27T09:20:34-07:00" level="fatal" msg="write /dev/stdout: broken pipe" 
```

The next image seems to work but the verbose output looks wrong.  It looks like it added the squashed layer at the end when it should be just after the from layer ID.  Everything that points up to it should be squashed into that new layer.  Not sure if the logging output is incorrect or if it's squashing incorrectly.

**Comment by rafecolton** [comment]
Could you give me a little more info about the first image, perhaps a `Dockerfile`?  That error should never be reached unless the image is malformed (or there's a logic error, which is more likely).  Does anything catch your eye in [this code](https://github.com/winchman/libsquash/blob/8e4a8a06cf43d370904c22b91793a31f34e35333/export_traversal.go#L33-L47)?

As for the second image - the logging output is correct.  I made a change to move the squash layer to last for reasons explained in [this pull request](https://github.com/winchman/libsquash/pull/9).  However, there may very well be use cases I have not considered.  Could you elaborate on the reason for inserting the squash layer immediately after the from layer?

**Comment by jwilder** [comment]
I'll see if I can create a Dockerfile that will reproduce the error.  The image I tried I can't share, but it is working w/ the current version of docker-squash.

The main reason I inserted the squashed layer somewhere in the middle is because of the `-from` argument.    `-from` allows you to squash all the child layers from a parent layer.  By default, it would choose the root layer as the from layer.  Using a different layer is useful for images that extend multiple base images that don't change frequently.  In my docker use, I have several base images that extend some of public base images.  For example, a `base-python` that installs some standard python libraries and tools that has a parent `FROM debian:wheezy`.  Then I have other base images that are `FROM base-python`.  When building my `base-python` type images, I use `-from` so that I don't also squash all of `debian:wheezy` into each of those base images.  When building out hosts, I pre-bake those base layers onto the host image so they don't need to be pulled when starting my actual containers.

Another reason is that it seems more logical to me to squash child layers into their parents vs all the parents into a child.  With the squashed layer inserted higher up in the history, all the heavy layers are at the top and small history layers are at the bottom (in `docker history` representation).  When I look at a squashed image w/ the layer inserted at the end, I see a a big squahed layer at the bottom with a parent pointing to the `CMD` layer which seems wrong to me.  Not sure if it matters to docker but it seems like the `CMD` or `ENTRYPOINT` layer should be last.

**Comment by rafecolton** [comment]
Hi, just wanted to follow up to say that I'm working on the required updates to `libsquash` in [this](https://github.com/winchman/libsquash/tree/add-tag-and-from-options) branch.  I will follow up on this pull request when they are ready

**Comment by zamotivator** [comment]
Could you please update README?

**Pull request closed without merging**
